// Research index.
window.TEI_RESEARCH = [
  {
    "id": "2026-10-03-crude-returns-products-lag-diesel-market",
    "title": "The Crude Is Back, the Diesel Is Not: Why October's Oil Market Is a Products Market",
    "date": "2026-10-03",
    "dateDisplay": "3 October 2026",
    "year": "2026",
    "author": "Dr. Ali Ahmad",
    "authorSlug": "dr-ali-ahmad",
    "region": "global",
    "regionLabel": "Global",
    "href": "articles/2026-10-03-crude-returns-products-lag-diesel-market.html"
  },
  {
    "id": "2026-10-03-furnace-oil-rlng-winter-hedge",
    "title": "Furnace Oil Is Pakistan's Hedge Against Spot LNG. It Needs to Become a Plan.",
    "date": "2026-10-03",
    "dateDisplay": "3 October 2026",
    "year": "2026",
    "author": "Bilal Mohyuddin",
    "authorSlug": "bilal-mohyuddin",
    "region": "pakistan",
    "regionLabel": "Pakistan",
    "href": "articles/2026-10-03-furnace-oil-rlng-winter-hedge.html"
  },
  {
    "id": "2026-10-02-imf-review-bisp-power-subsidy-cash-transfer",
    "title": "Cash Through BISP, Debt Through Islamabad: What the IMF Review Can and Cannot Fix in Power Subsidies",
    "date": "2026-10-02",
    "dateDisplay": "2 October 2026",
    "year": "2026",
    "author": "Nadia Qureshi",
    "authorSlug": "nadia-qureshi",
    "region": "pakistan",
    "regionLabel": "Pakistan",
    "href": "articles/2026-10-02-imf-review-bisp-power-subsidy-cash-transfer.html"
  },
  {
    "id": "2026-10-02-asian-seaborne-coal-gulf-lng-outage",
    "title": "Coal as Asia's Shock Absorber: Seaborne Thermal Coal during the 2026 Gulf LNG Outage",
    "date": "2026-10-02",
    "dateDisplay": "2 October 2026",
    "year": "2026",
    "author": "Hassan Raza",
    "authorSlug": "hassan-raza",
    "region": "global",
    "regionLabel": "Global",
    "href": "articles/2026-10-02-asian-seaborne-coal-gulf-lng-outage.html"
  },
  {
    "id": "2026-10-02-rooftop-solar-back-at-the-disco-desk",
    "title": "Rooftop Solar Back at the DISCO Desk: The 25 kW Approval and the 80% Transformer Ceiling",
    "date": "2026-10-02",
    "dateDisplay": "2 October 2026",
    "year": "2026",
    "author": "Sana Iqbal",
    "authorSlug": "sana-iqbal",
    "region": "pakistan",
    "regionLabel": "Pakistan",
    "href": "articles/2026-10-02-rooftop-solar-back-at-the-disco-desk.html"
  },
  {
    "id": "2026-10-01-henry-hub-storage-gap-gulf-coast-salt",
    "title": "Three-Dollar Henry Hub Is a Liquefaction Ceiling, Not a Storage Cushion",
    "date": "2026-10-01",
    "dateDisplay": "1 October 2026",
    "year": "2026",
    "author": "Claire Dunne",
    "authorSlug": "claire-dunne",
    "region": "united-states",
    "regionLabel": "United States",
    "href": "articles/2026-10-01-henry-hub-storage-gap-gulf-coast-salt.html"
  },
  {
    "id": "2026-09-30-pjm-backstop-procurement-pause",
    "title": "PJM's Backstop Procurement Pause: Re-size the 6.8 GW Target Before It Is Bought",
    "date": "2026-09-30",
    "dateDisplay": "30 September 2026",
    "year": "2026",
    "author": "Marcus Hale",
    "authorSlug": "marcus-hale",
    "region": "united-states",
    "regionLabel": "United States",
    "href": "articles/2026-09-30-pjm-backstop-procurement-pause.html"
  },
  {
    "id": "2026-09-30-pjm-order-1920-cost-allocation-impasse",
    "title": "PJM's Order 1920 Cost Allocation Impasse: Two Proposals, One Tariff and a Pending Fourth Circuit Ruling",
    "date": "2026-09-30",
    "dateDisplay": "30 September 2026",
    "year": "2026",
    "author": "Claire Dunne",
    "authorSlug": "claire-dunne",
    "region": "united-states",
    "regionLabel": "United States",
    "href": "articles/2026-09-30-pjm-order-1920-cost-allocation-impasse.html"
  },
  {
    "id": "2026-09-29-ercot-batch-zero-conditional-classifications",
    "title": "ERCOT Batch Zero Conditional Classifications: 66.4 GW Base, 127.9 GW Studied, December Verification Ahead",
    "date": "2026-09-29",
    "dateDisplay": "29 September 2026",
    "year": "2026",
    "author": "Claire Dunne",
    "authorSlug": "claire-dunne",
    "region": "united-states",
    "regionLabel": "United States",
    "href": "articles/2026-09-29-ercot-batch-zero-conditional-classifications.html"
  },
  {
    "id": "2026-09-29-ercot-soft-lmps-large-load-premium",
    "title": "Soft September LMPs, Hard Large-Load Queues",
    "date": "2026-09-29",
    "dateDisplay": "29 September 2026",
    "year": "2026",
    "author": "Marcus Hale",
    "authorSlug": "marcus-hale",
    "region": "united-states",
    "regionLabel": "United States",
    "href": "articles/2026-09-29-ercot-soft-lmps-large-load-premium.html"
  },
  {
    "id": "2026-09-28-hormuz-partial-reopening-and-export-rebound",
    "title": "Hormuz Partial Reopening and the September Export Rebound",
    "date": "2026-09-28",
    "dateDisplay": "28 September 2026",
    "year": "2026",
    "author": "Jamshed Khan",
    "authorSlug": "jamshed-khan",
    "region": "middle-east",
    "regionLabel": "Middle East",
    "href": "articles/2026-09-28-hormuz-partial-reopening-and-export-rebound.html"
  },
  {
    "id": "2026-09-25-ke-ngc-interconnection-planning",
    "title": "KE and NGC Interconnection in IGCEP Sensitivities: One Country, Two Grids",
    "date": "2026-09-25",
    "dateDisplay": "25 September 2026",
    "year": "2026",
    "author": "Sana Iqbal",
    "authorSlug": "sana-iqbal",
    "region": "pakistan",
    "regionLabel": "Pakistan",
    "href": "articles/2026-09-25-ke-ngc-interconnection-planning.html"
  },
  {
    "id": "2026-09-18-disco-stake-sale-management-control",
    "title": "Selling 51 to 100 Per Cent of DISCOs with Management Control",
    "date": "2026-09-18",
    "dateDisplay": "18 September 2026",
    "year": "2026",
    "author": "Hassan Raza",
    "authorSlug": "hassan-raza",
    "region": "pakistan",
    "regionLabel": "Pakistan",
    "href": "articles/2026-09-18-disco-stake-sale-management-control.html"
  },
  {
    "id": "2026-09-14-oil-geopolitics-middle-east-tensions",
    "title": "Oil geopolitics in September 2026: Middle East tension, Hormuz maths, OPEC+ barrels",
    "date": "2026-09-14",
    "dateDisplay": "14 September 2026",
    "year": "2026",
    "author": "Sana Iqbal",
    "authorSlug": "sana-iqbal",
    "region": "global",
    "regionLabel": "Global",
    "href": "articles/2026-09-14-oil-geopolitics-middle-east-tensions.html"
  },
  {
    "id": "2026-09-14-steo-record-electricity-sales-data-centres",
    "title": "Record United States Electricity Sales in the September 2026 STEO: Data Centres and Manufacturing",
    "date": "2026-09-14",
    "dateDisplay": "14 September 2026",
    "year": "2026",
    "author": "Marcus Hale",
    "authorSlug": "marcus-hale",
    "region": "united-states",
    "regionLabel": "United States",
    "href": "articles/2026-09-14-steo-record-electricity-sales-data-centres.html"
  },
  {
    "id": "2026-09-12-brent-steo-middle-east-disruption-prices",
    "title": "Brent under Middle East disruption: EIA STEO prices, shut-ins, and inventory draws",
    "date": "2026-09-12",
    "dateDisplay": "12 September 2026",
    "year": "2026",
    "author": "Sana Iqbal",
    "authorSlug": "sana-iqbal",
    "region": "middle-east",
    "regionLabel": "Middle East",
    "href": "articles/2026-09-12-brent-steo-middle-east-disruption-prices.html"
  },
  {
    "id": "2026-09-12-hybrids-bess-wheeling-mandate",
    "title": "Hybrids and Mandatory BESS: How IGCEP and Wheeling Finally Meet Storage",
    "date": "2026-09-12",
    "dateDisplay": "12 September 2026",
    "year": "2026",
    "author": "Nadia Qureshi",
    "authorSlug": "nadia-qureshi",
    "region": "pakistan",
    "regionLabel": "Pakistan",
    "href": "articles/2026-09-12-hybrids-bess-wheeling-mandate.html"
  },
  {
    "id": "2026-09-10-igcep-2027-data-collection",
    "title": "IGCEP 2027 Data Calls While IGCEP 2025-35 Awaits Notification",
    "date": "2026-09-10",
    "dateDisplay": "10 September 2026",
    "year": "2026",
    "author": "Bilal Mohyuddin",
    "authorSlug": "bilal-mohyuddin",
    "region": "pakistan",
    "regionLabel": "Pakistan",
    "href": "articles/2026-09-10-igcep-2027-data-collection.html"
  },
  {
    "id": "2026-09-07-european-power-prices-renewables",
    "title": "European power into autumn 2026: high renewables, weather risk, and industrial bills",
    "date": "2026-09-07",
    "dateDisplay": "7 September 2026",
    "year": "2026",
    "author": "Hassan Raza",
    "authorSlug": "hassan-raza",
    "region": "global",
    "regionLabel": "Global",
    "href": "articles/2026-09-07-european-power-prices-renewables.html"
  },
  {
    "id": "2026-09-06-cleared-pending-solar-applications",
    "title": "Eleven Thousand Cleared Solar Cases and the Remainder Still Waiting",
    "date": "2026-09-06",
    "dateDisplay": "6 September 2026",
    "year": "2026",
    "author": "Dr. Ali Ahmad",
    "authorSlug": "dr-ali-ahmad",
    "region": "pakistan",
    "regionLabel": "Pakistan",
    "href": "articles/2026-09-06-cleared-pending-solar-applications.html"
  },
  {
    "id": "2026-08-26-pending-rooftop-solar-cases",
    "title": "Pending Solar Connections after Net Billing: Clearing the Grey Zone",
    "date": "2026-08-26",
    "dateDisplay": "26 August 2026",
    "year": "2026",
    "author": "M. Ali Janjua",
    "authorSlug": "m-ali-janjua",
    "region": "pakistan",
    "regionLabel": "Pakistan",
    "href": "articles/2026-08-26-pending-rooftop-solar-cases.html"
  },
  {
    "id": "2026-08-24-china-ev-battery-minerals-demand",
    "title": "China, EVs and battery materials: demand power meets supply-chain chokepoints",
    "date": "2026-08-24",
    "dateDisplay": "24 August 2026",
    "year": "2026",
    "author": "Nadia Qureshi",
    "authorSlug": "nadia-qureshi",
    "region": "global",
    "regionLabel": "Global",
    "href": "articles/2026-08-24-china-ev-battery-minerals-demand.html"
  },
  {
    "id": "2026-08-18-power-markets-and-oil-gas-price-shock",
    "title": "Power Markets under the 2026 Oil and Gas Price Shock",
    "date": "2026-08-18",
    "dateDisplay": "18 August 2026",
    "year": "2026",
    "author": "Hassan Raza",
    "authorSlug": "hassan-raza",
    "region": "middle-east",
    "regionLabel": "Middle East",
    "href": "articles/2026-08-18-power-markets-and-oil-gas-price-shock.html"
  },
  {
    "id": "2026-08-17-ercot-large-load-pause-verification",
    "title": "ERCOT Pauses Batch Zero Study and Large Data-Centre Energisation after Abbott Directive",
    "date": "2026-08-17",
    "dateDisplay": "17 August 2026",
    "year": "2026",
    "author": "Marcus Hale",
    "authorSlug": "marcus-hale",
    "region": "united-states",
    "regionLabel": "United States",
    "href": "articles/2026-08-17-ercot-large-load-pause-verification.html"
  },
  {
    "id": "2026-08-17-us-gas-exports-growth-path-to-2027",
    "title": "United States Natural Gas Exports on Course to Rise Nearly Thirty Percent by 2027",
    "date": "2026-08-17",
    "dateDisplay": "17 August 2026",
    "year": "2026",
    "author": "Jamshed Khan",
    "authorSlug": "jamshed-khan",
    "region": "united-states",
    "regionLabel": "United States",
    "href": "articles/2026-08-17-us-gas-exports-growth-path-to-2027.html"
  },
  {
    "id": "2026-08-10-igu-world-lng-report-2026-record",
    "title": "IGU World LNG Report 2026: record trade, investment surge, Europe rebound",
    "date": "2026-08-10",
    "dateDisplay": "10 August 2026",
    "year": "2026",
    "author": "Bilal Mohyuddin",
    "authorSlug": "bilal-mohyuddin",
    "region": "global",
    "regionLabel": "Global",
    "href": "articles/2026-08-10-igu-world-lng-report-2026-record.html"
  },
  {
    "id": "2026-07-28-disco-spv-fesco-gepco-iesco",
    "title": "A Rs250 Billion SPV to Carve Out DISCO Liabilities for Sale",
    "date": "2026-07-28",
    "dateDisplay": "28 July 2026",
    "year": "2026",
    "author": "Jamshed Khan",
    "authorSlug": "jamshed-khan",
    "region": "pakistan",
    "regionLabel": "Pakistan",
    "href": "articles/2026-07-28-disco-spv-fesco-gepco-iesco.html"
  },
  {
    "id": "2026-07-13-shipping-cape-route-cumulative-costs",
    "title": "Cape routing as the new normal: cumulative costs of avoided Red Sea passages",
    "date": "2026-07-13",
    "dateDisplay": "13 July 2026",
    "year": "2026",
    "author": "Dr. Ali Ahmad",
    "authorSlug": "dr-ali-ahmad",
    "region": "global",
    "regionLabel": "Global",
    "href": "articles/2026-07-13-shipping-cape-route-cumulative-costs.html"
  },
  {
    "id": "2026-07-13-national-transmission-needs-study-draft",
    "title": "DOE’s Draft 2026 National Transmission Needs Study: Congestion, Seams and Data-Centre Load",
    "date": "2026-07-13",
    "dateDisplay": "13 July 2026",
    "year": "2026",
    "author": "Claire Dunne",
    "authorSlug": "claire-dunne",
    "region": "united-states",
    "regionLabel": "United States",
    "href": "articles/2026-07-13-national-transmission-needs-study-draft.html"
  },
  {
    "id": "2026-06-16-qatar-lng-hormuz-and-ras-laffan",
    "title": "Qatar LNG, Hormuz Transit Risk and Damage at Ras Laffan",
    "date": "2026-06-16",
    "dateDisplay": "16 June 2026",
    "year": "2026",
    "author": "Nadia Qureshi",
    "authorSlug": "nadia-qureshi",
    "region": "middle-east",
    "regionLabel": "Middle East",
    "href": "articles/2026-06-16-qatar-lng-hormuz-and-ras-laffan.html"
  },
  {
    "id": "2026-06-15-coal-phase-down-asia-trade",
    "title": "Coal phase-down rhetoric versus Asia-Pacific trade reality",
    "date": "2026-06-15",
    "dateDisplay": "15 June 2026",
    "year": "2026",
    "author": "M. Ali Janjua",
    "authorSlug": "m-ali-janjua",
    "region": "global",
    "regionLabel": "Global",
    "href": "articles/2026-06-15-coal-phase-down-asia-trade.html"
  },
  {
    "id": "2026-05-18-middle-east-lng-qatar-gulf-exports",
    "title": "Middle East LNG in a record trade system: Gulf molecules and maritime risk",
    "date": "2026-05-18",
    "dateDisplay": "18 May 2026",
    "year": "2026",
    "author": "Jamshed Khan",
    "authorSlug": "jamshed-khan",
    "region": "global",
    "regionLabel": "Global",
    "href": "articles/2026-05-18-middle-east-lng-qatar-gulf-exports.html"
  },
  {
    "id": "2026-05-12-opec-spare-capacity-under-gulf-disruption",
    "title": "OPEC+ spare capacity under Gulf disruption: IEA tables and deliverability",
    "date": "2026-05-12",
    "dateDisplay": "12 May 2026",
    "year": "2026",
    "author": "Bilal Mohyuddin",
    "authorSlug": "bilal-mohyuddin",
    "region": "middle-east",
    "regionLabel": "Middle East",
    "href": "articles/2026-05-12-opec-spare-capacity-under-gulf-disruption.html"
  },
  {
    "id": "2026-04-14-iran-crude-exports-eia-vortexa-record",
    "title": "Iranian crude exports on the public record: EIA, Vortexa, and IEA readings",
    "date": "2026-04-14",
    "dateDisplay": "14 April 2026",
    "year": "2026",
    "author": "Dr. Ali Ahmad",
    "authorSlug": "dr-ali-ahmad",
    "region": "middle-east",
    "regionLabel": "Middle East",
    "href": "articles/2026-04-14-iran-crude-exports-eia-vortexa-record.html"
  },
  {
    "id": "2026-03-10-hormuz-crude-transit-documented-flows",
    "title": "Hormuz crude transit under conflict risk: documented flows, not slogans",
    "date": "2026-03-10",
    "dateDisplay": "10 March 2026",
    "year": "2026",
    "author": "Jamshed Khan",
    "authorSlug": "jamshed-khan",
    "region": "middle-east",
    "regionLabel": "Middle East",
    "href": "articles/2026-03-10-hormuz-crude-transit-documented-flows.html"
  },
  {
    "id": "2026-03-10-hormuz-oil-transit-collapse-iea",
    "title": "Strait of Hormuz Oil Transit Collapse and the Global Supply Response",
    "date": "2026-03-10",
    "dateDisplay": "10 March 2026",
    "year": "2026",
    "author": "M. Ali Janjua",
    "authorSlug": "m-ali-janjua",
    "region": "middle-east",
    "regionLabel": "Middle East",
    "href": "articles/2026-03-10-hormuz-oil-transit-collapse-iea.html"
  },
  {
    "id": "2025-12-15-lng-contracting-europe-demand-uncertainty",
    "title": "LNG contracting under European demand uncertainty into 2030",
    "date": "2025-12-15",
    "dateDisplay": "15 December 2025",
    "year": "2025",
    "author": "Sana Iqbal",
    "authorSlug": "sana-iqbal",
    "region": "global",
    "regionLabel": "Global",
    "href": "articles/2025-12-15-lng-contracting-europe-demand-uncertainty.html"
  },
  {
    "id": "2025-12-15-coal-retirement-delays-and-emergency-orders",
    "title": "When Planned Coal Exits Meet Reliability Politics: Watching the 2025 Retirement Docket",
    "date": "2025-12-15",
    "dateDisplay": "15 December 2025",
    "year": "2025",
    "author": "Marcus Hale",
    "authorSlug": "marcus-hale",
    "region": "united-states",
    "regionLabel": "United States",
    "href": "articles/2025-12-15-coal-retirement-delays-and-emergency-orders.html"
  },
  {
    "id": "2025-12-10-circular-debt-stock-vs-flow",
    "title": "After a Year of Reform Rhetoric: Is Circular Debt Flow Actually Slowing?",
    "date": "2025-12-10",
    "dateDisplay": "10 December 2025",
    "year": "2025",
    "author": "Sana Iqbal",
    "authorSlug": "sana-iqbal",
    "region": "pakistan",
    "regionLabel": "Pakistan",
    "href": "articles/2025-12-10-circular-debt-stock-vs-flow.html"
  },
  {
    "id": "2025-11-17-china-lng-coal-power-dual",
    "title": "China's dual energy reality: coal import swings and LNG optionality",
    "date": "2025-11-17",
    "dateDisplay": "17 November 2025",
    "year": "2025",
    "author": "Hassan Raza",
    "authorSlug": "hassan-raza",
    "region": "global",
    "regionLabel": "Global",
    "href": "articles/2025-11-17-china-lng-coal-power-dual.html"
  },
  {
    "id": "2025-11-17-federal-energy-dominance-and-gas-markets",
    "title": "Energy Dominance Rhetoric and the Engineering Reality of United States Gas Markets",
    "date": "2025-11-17",
    "dateDisplay": "17 November 2025",
    "year": "2025",
    "author": "M. Ali Janjua",
    "authorSlug": "m-ali-janjua",
    "region": "united-states",
    "regionLabel": "United States",
    "href": "articles/2025-11-17-federal-energy-dominance-and-gas-markets.html"
  },
  {
    "id": "2025-11-04-eni-lng-cargo-cancellations",
    "title": "Cancelling Eni Cargoes: Contract Flexibility Meets Soft Offtake",
    "date": "2025-11-04",
    "dateDisplay": "4 November 2025",
    "year": "2025",
    "author": "Hassan Raza",
    "authorSlug": "hassan-raza",
    "region": "pakistan",
    "regionLabel": "Pakistan",
    "href": "articles/2025-11-04-eni-lng-cargo-cancellations.html"
  },
  {
    "id": "2025-10-14-ders-disco-igcep-inputs",
    "title": "Distributed Energy in IGCEP: Planning for the Solar the DISCOs Already Host",
    "date": "2025-10-14",
    "dateDisplay": "14 October 2025",
    "year": "2025",
    "author": "Nadia Qureshi",
    "authorSlug": "nadia-qureshi",
    "region": "pakistan",
    "regionLabel": "Pakistan",
    "href": "articles/2025-10-14-ders-disco-igcep-inputs.html"
  },
  {
    "id": "2025-10-13-oil-market-non-opec-supply-surplus-risk",
    "title": "Oil balances into late 2025: non-OPEC supply, China plateau, OPEC+ glide path",
    "date": "2025-10-13",
    "dateDisplay": "13 October 2025",
    "year": "2025",
    "author": "Nadia Qureshi",
    "authorSlug": "nadia-qureshi",
    "region": "global",
    "regionLabel": "Global",
    "href": "articles/2025-10-13-oil-market-non-opec-supply-surplus-risk.html"
  },
  {
    "id": "2025-10-13-colocated-large-loads-and-tariff-design",
    "title": "Co-Located Large Loads: Tariff Design Before the Next Data-Centre Wave",
    "date": "2025-10-13",
    "dateDisplay": "13 October 2025",
    "year": "2025",
    "author": "Marcus Hale",
    "authorSlug": "marcus-hale",
    "region": "united-states",
    "regionLabel": "United States",
    "href": "articles/2025-10-13-colocated-large-loads-and-tariff-design.html"
  },
  {
    "id": "2025-09-15-european-electricity-flexibility-gap",
    "title": "European electricity: renewables deliver, flexibility still under-ordered",
    "date": "2025-09-15",
    "dateDisplay": "15 September 2025",
    "year": "2025",
    "author": "Bilal Mohyuddin",
    "authorSlug": "bilal-mohyuddin",
    "region": "global",
    "regionLabel": "Global",
    "href": "articles/2025-09-15-european-electricity-flexibility-gap.html"
  },
  {
    "id": "2025-09-15-fy25-generation-mix",
    "title": "Reading FY2025’s Generation Mix: Hydro, Nuclear, and Coal Shares",
    "date": "2025-09-15",
    "dateDisplay": "15 September 2025",
    "year": "2025",
    "author": "Bilal Mohyuddin",
    "authorSlug": "bilal-mohyuddin",
    "region": "pakistan",
    "regionLabel": "Pakistan",
    "href": "articles/2025-09-15-fy25-generation-mix.html"
  },
  {
    "id": "2025-09-15-renewables-share-electricity-generation",
    "title": "Renewables Toward a Quarter of United States Generation: Share Gains and Firm-Capacity Caveats",
    "date": "2025-09-15",
    "dateDisplay": "15 September 2025",
    "year": "2025",
    "author": "Claire Dunne",
    "authorSlug": "claire-dunne",
    "region": "united-states",
    "regionLabel": "United States",
    "href": "articles/2025-09-15-renewables-share-electricity-generation.html"
  },
  {
    "id": "2025-08-20-igcep-2025-35-revision",
    "title": "IGCEP 2025-35: Revising the Plan While Demand Shifts under Solar",
    "date": "2025-08-20",
    "dateDisplay": "20 August 2025",
    "year": "2025",
    "author": "Dr. Ali Ahmad",
    "authorSlug": "dr-ali-ahmad",
    "region": "pakistan",
    "regionLabel": "Pakistan",
    "href": "articles/2025-08-20-igcep-2025-35-revision.html"
  },
  {
    "id": "2025-08-18-middle-east-spare-capacity-oil",
    "title": "Middle East supply, spare capacity, and the cost of defending price",
    "date": "2025-08-18",
    "dateDisplay": "18 August 2025",
    "year": "2025",
    "author": "Dr. Ali Ahmad",
    "authorSlug": "dr-ali-ahmad",
    "region": "global",
    "regionLabel": "Global",
    "href": "articles/2025-08-18-middle-east-spare-capacity-oil.html"
  },
  {
    "id": "2025-08-18-transmission-investment-gap-load-growth",
    "title": "The Transmission Investment Gap as United States Load Growth Reappears",
    "date": "2025-08-18",
    "dateDisplay": "18 August 2025",
    "year": "2025",
    "author": "Marcus Hale",
    "authorSlug": "marcus-hale",
    "region": "united-states",
    "regionLabel": "United States",
    "href": "articles/2025-08-18-transmission-investment-gap-load-growth.html"
  },
  {
    "id": "2025-07-21-pm-blocks-net-metering-review",
    "title": "The Prime Minister’s Third Pause on Net-Metering Revision",
    "date": "2025-07-21",
    "dateDisplay": "21 July 2025",
    "year": "2025",
    "author": "M. Ali Janjua",
    "authorSlug": "m-ali-janjua",
    "region": "pakistan",
    "regionLabel": "Pakistan",
    "href": "articles/2025-07-21-pm-blocks-net-metering-review.html"
  },
  {
    "id": "2025-07-14-shipping-chokepoints-energy-security",
    "title": "Shipping chokepoints after eighteen months of Red Sea diversion",
    "date": "2025-07-14",
    "dateDisplay": "14 July 2025",
    "year": "2025",
    "author": "M. Ali Janjua",
    "authorSlug": "m-ali-janjua",
    "region": "global",
    "regionLabel": "Global",
    "href": "articles/2025-07-14-shipping-chokepoints-energy-security.html"
  },
  {
    "id": "2025-07-14-nuclear-smr-licensing-after-advance-act",
    "title": "One Year After the ADVANCE Act: SMRs, Licensing Milestones and Grid Reality",
    "date": "2025-07-14",
    "dateDisplay": "14 July 2025",
    "year": "2025",
    "author": "Claire Dunne",
    "authorSlug": "claire-dunne",
    "region": "united-states",
    "regionLabel": "United States",
    "href": "articles/2025-07-14-nuclear-smr-licensing-after-advance-act.html"
  },
  {
    "id": "2025-06-18-local-vs-imported-coal",
    "title": "Local Coal versus Imported Coal on the Merit Order",
    "date": "2025-06-18",
    "dateDisplay": "18 June 2025",
    "year": "2025",
    "author": "Jamshed Khan",
    "authorSlug": "jamshed-khan",
    "region": "pakistan",
    "regionLabel": "Pakistan",
    "href": "articles/2025-06-18-local-vs-imported-coal.html"
  },
  {
    "id": "2025-06-16-coal-trade-record-then-retreat",
    "title": "Coal trade after the 2024 record: Asia still rules the seaborne market",
    "date": "2025-06-16",
    "dateDisplay": "16 June 2025",
    "year": "2025",
    "author": "Jamshed Khan",
    "authorSlug": "jamshed-khan",
    "region": "global",
    "regionLabel": "Global",
    "href": "articles/2025-06-16-coal-trade-record-then-retreat.html"
  },
  {
    "id": "2025-06-16-ercot-load-growth-and-reliability",
    "title": "ERCOT Load Growth, Data Centres and the Texas Reliability Problem Set",
    "date": "2025-06-16",
    "dateDisplay": "16 June 2025",
    "year": "2025",
    "author": "Marcus Hale",
    "authorSlug": "marcus-hale",
    "region": "united-states",
    "regionLabel": "United States",
    "href": "articles/2025-06-16-ercot-load-growth-and-reliability.html"
  },
  {
    "id": "2024-12-16-opec-plus-delays-unwind-to-april-2025",
    "title": "OPEC+ delays the unwind to April 2025 and stretches cuts toward 2026",
    "date": "2024-12-16",
    "dateDisplay": "16 December 2024",
    "year": "2024",
    "author": "Sana Iqbal",
    "authorSlug": "sana-iqbal",
    "region": "global",
    "regionLabel": "Global",
    "href": "articles/2024-12-16-opec-plus-delays-unwind-to-april-2025.html"
  },
  {
    "id": "2024-12-16-us-lng-exports-2024-year-end",
    "title": "United States LNG in 2024: Still the World Leader, Flat Volumes, Shifting Destinations",
    "date": "2024-12-16",
    "dateDisplay": "16 December 2024",
    "year": "2024",
    "author": "Jamshed Khan",
    "authorSlug": "jamshed-khan",
    "region": "united-states",
    "regionLabel": "United States",
    "href": "articles/2024-12-16-us-lng-exports-2024-year-end.html"
  },
  {
    "id": "2024-12-04-ipp-ppa-renegotiation",
    "title": "Renegotiating IPPs: Compensation, Take-and-Pay, and the Credibility Test",
    "date": "2024-12-04",
    "dateDisplay": "4 December 2024",
    "year": "2024",
    "author": "Sana Iqbal",
    "authorSlug": "sana-iqbal",
    "region": "pakistan",
    "regionLabel": "Pakistan",
    "href": "articles/2024-12-04-ipp-ppa-renegotiation.html"
  },
  {
    "id": "2024-11-18-nuclear-licence-renewals-and-fleet-value",
    "title": "Existing Nuclear Licence Renewals and Why the Operating Fleet Still Anchors Firm Supply",
    "date": "2024-11-18",
    "dateDisplay": "18 November 2024",
    "year": "2024",
    "author": "Marcus Hale",
    "authorSlug": "marcus-hale",
    "region": "united-states",
    "regionLabel": "United States",
    "href": "articles/2024-11-18-nuclear-licence-renewals-and-fleet-value.html"
  },
  {
    "id": "2024-11-11-lng-trade-atlantic-pacific-rebalancing",
    "title": "LNG's Atlantic-Pacific rebalancing: Europe steps back, Asia steps in during 2024",
    "date": "2024-11-11",
    "dateDisplay": "11 November 2024",
    "year": "2024",
    "author": "Hassan Raza",
    "authorSlug": "hassan-raza",
    "region": "global",
    "regionLabel": "Global",
    "href": "articles/2024-11-11-lng-trade-atlantic-pacific-rebalancing.html"
  },
  {
    "id": "2024-10-15-thar-mine-expansion-finance",
    "title": "Thar Mine Expansion Meets Circular Debt: The Phase-III Financing Bind",
    "date": "2024-10-15",
    "dateDisplay": "15 October 2024",
    "year": "2024",
    "author": "Hassan Raza",
    "authorSlug": "hassan-raza",
    "region": "pakistan",
    "regionLabel": "Pakistan",
    "href": "articles/2024-10-15-thar-mine-expansion-finance.html"
  },
  {
    "id": "2024-10-14-red-sea-oil-flows-eia-assessment",
    "title": "Bab el-Mandeb halved: EIA's reading of Red Sea oil flows through August 2024",
    "date": "2024-10-14",
    "dateDisplay": "14 October 2024",
    "year": "2024",
    "author": "Nadia Qureshi",
    "authorSlug": "nadia-qureshi",
    "region": "global",
    "regionLabel": "Global",
    "href": "articles/2024-10-14-red-sea-oil-flows-eia-assessment.html"
  },
  {
    "id": "2024-10-14-pjm-capacity-reliability-rising-load",
    "title": "PJM Capacity and Reliability under Rising Large-Load Pressure",
    "date": "2024-10-14",
    "dateDisplay": "14 October 2024",
    "year": "2024",
    "author": "Claire Dunne",
    "authorSlug": "claire-dunne",
    "region": "united-states",
    "regionLabel": "United States",
    "href": "articles/2024-10-14-pjm-capacity-reliability-rising-load.html"
  },
  {
    "id": "2024-10-08-jhimpir-gharo-wind-curtailment",
    "title": "Jhimpir-Gharo Wind: Megawatts Without Wires Become NPMV Invoices",
    "date": "2024-10-08",
    "dateDisplay": "8 October 2024",
    "year": "2024",
    "author": "Nadia Qureshi",
    "authorSlug": "nadia-qureshi",
    "region": "pakistan",
    "regionLabel": "Pakistan",
    "href": "articles/2024-10-08-jhimpir-gharo-wind-curtailment.html"
  },
  {
    "id": "2024-09-30-imf-eff-energy-conditionality",
    "title": "The EFF’s Energy Conditions: Prices, Costs, and Private Participation",
    "date": "2024-09-30",
    "dateDisplay": "30 September 2024",
    "year": "2024",
    "author": "Bilal Mohyuddin",
    "authorSlug": "bilal-mohyuddin",
    "region": "pakistan",
    "regionLabel": "Pakistan",
    "href": "articles/2024-09-30-imf-eff-energy-conditionality.html"
  },
  {
    "id": "2024-09-18-utility-scale-solar-after-qasp",
    "title": "Utility-Scale Solar after Quaid-e-Azam: Parks, Pipelines, and Empty Auctions",
    "date": "2024-09-18",
    "dateDisplay": "18 September 2024",
    "year": "2024",
    "author": "Dr. Ali Ahmad",
    "authorSlug": "dr-ali-ahmad",
    "region": "pakistan",
    "regionLabel": "Pakistan",
    "href": "articles/2024-09-18-utility-scale-solar-after-qasp.html"
  },
  {
    "id": "2024-09-16-european-power-renewables-prices",
    "title": "European power in 2024: renewables climb, wholesale prices ease, flexibility lags",
    "date": "2024-09-16",
    "dateDisplay": "16 September 2024",
    "year": "2024",
    "author": "Bilal Mohyuddin",
    "authorSlug": "bilal-mohyuddin",
    "region": "global",
    "regionLabel": "Global",
    "href": "articles/2024-09-16-european-power-renewables-prices.html"
  },
  {
    "id": "2024-09-16-interconnection-queue-cluster-study-rollout",
    "title": "Cluster Studies Take Hold: What Order No. 2023 Means on the Ground in Late 2024",
    "date": "2024-09-16",
    "dateDisplay": "16 September 2024",
    "year": "2024",
    "author": "Marcus Hale",
    "authorSlug": "marcus-hale",
    "region": "united-states",
    "regionLabel": "United States",
    "href": "articles/2024-09-16-interconnection-queue-cluster-study-rollout.html"
  },
  {
    "id": "2024-09-09-opec-plus-delays-unwind-two-months",
    "title": "OPEC+ delays the unwind: two more months of voluntary cuts and the compliance test",
    "date": "2024-09-09",
    "dateDisplay": "9 September 2024",
    "year": "2024",
    "author": "Dr. Ali Ahmad",
    "authorSlug": "dr-ali-ahmad",
    "region": "global",
    "regionLabel": "Global",
    "href": "articles/2024-09-09-opec-plus-delays-unwind-two-months.html"
  },
  {
    "id": "2024-08-22-rooftop-solar-net-metering-boom",
    "title": "Rooftop Solar’s Boom Is a Grid Pricing Problem in Disguise",
    "date": "2024-08-22",
    "dateDisplay": "22 August 2024",
    "year": "2024",
    "author": "M. Ali Janjua",
    "authorSlug": "m-ali-janjua",
    "region": "pakistan",
    "regionLabel": "Pakistan",
    "href": "articles/2024-08-22-rooftop-solar-net-metering-boom.html"
  },
  {
    "id": "2024-08-19-middle-east-supply-hormuz-security",
    "title": "Middle East supply security and the Strait of Hormuz in a diverted Red Sea year",
    "date": "2024-08-19",
    "dateDisplay": "19 August 2024",
    "year": "2024",
    "author": "M. Ali Janjua",
    "authorSlug": "m-ali-janjua",
    "region": "global",
    "regionLabel": "Global",
    "href": "articles/2024-08-19-middle-east-supply-hormuz-security.html"
  },
  {
    "id": "2024-08-19-henry-hub-lng-feedgas-power-competition",
    "title": "Henry Hub, LNG Feedgas and the Contest for United States Molecules",
    "date": "2024-08-19",
    "dateDisplay": "19 August 2024",
    "year": "2024",
    "author": "M. Ali Janjua",
    "authorSlug": "m-ali-janjua",
    "region": "united-states",
    "regionLabel": "United States",
    "href": "articles/2024-08-19-henry-hub-lng-feedgas-power-competition.html"
  },
  {
    "id": "2024-08-05-coal-to-gas-replacements-and-retirement-economics",
    "title": "Coal-to-Gas Replacements and the Economics Behind United States Steam Retirements",
    "date": "2024-08-05",
    "dateDisplay": "5 August 2024",
    "year": "2024",
    "author": "Marcus Hale",
    "authorSlug": "marcus-hale",
    "region": "united-states",
    "regionLabel": "United States",
    "href": "articles/2024-08-05-coal-to-gas-replacements-and-retirement-economics.html"
  },
  {
    "id": "2024-07-25-tariff-rebasing-imf-conditionality",
    "title": "July 2024 Tariff Rebasing and the Limits of Price-Only Reform",
    "date": "2024-07-25",
    "dateDisplay": "25 July 2024",
    "year": "2024",
    "author": "Jamshed Khan",
    "authorSlug": "jamshed-khan",
    "region": "pakistan",
    "regionLabel": "Pakistan",
    "href": "articles/2024-07-25-tariff-rebasing-imf-conditionality.html"
  },
  {
    "id": "2024-07-15-global-coal-trade-asia-pacific",
    "title": "Asia-Pacific coal trade: records, swing suppliers, and the slow bend in the curve",
    "date": "2024-07-15",
    "dateDisplay": "15 July 2024",
    "year": "2024",
    "author": "Jamshed Khan",
    "authorSlug": "jamshed-khan",
    "region": "global",
    "regionLabel": "Global",
    "href": "articles/2024-07-15-global-coal-trade-asia-pacific.html"
  },
  {
    "id": "2024-07-15-advance-act-nuclear-licensing-reform",
    "title": "The ADVANCE Act Becomes Law: Nuclear Licensing Reform Without Magical Thinking",
    "date": "2024-07-15",
    "dateDisplay": "15 July 2024",
    "year": "2024",
    "author": "Claire Dunne",
    "authorSlug": "claire-dunne",
    "region": "united-states",
    "regionLabel": "United States",
    "href": "articles/2024-07-15-advance-act-nuclear-licensing-reform.html"
  }
];
